FROM debian:latest
RUN apt-get update
RUN apt-get install -y \
    python3=3.9.13-1 \
    python3-pip \
    google-chrome-stable
RUN rm -rf /var/lib/apt/lists/*
COPY . /app
WORKDIR /app
RUN pip3 install -r requirements.txt
CMD ["pytest"]
