version: "3.4"

services:
  allure:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:39533"
    volumes:
      - ./results:/root/results

  db_test_database:
    container_name: db_test_database
    image: postgres:15-alpine
    shm_size: 128mb
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - C:/Users/metel/PycharmProjects/test-automation-suite/sql_file/demo-medium-20170815.sql:/docker-entrypoint-initdb.d/demo-medium-20170815.sql
    