version: "3.4"

services:
  allure:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:39533"
    volumes:
      - ./results:/root/results

  db_demo-medium:
    container_name: db_demo-medium
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
    image: postgres:15-alpine
    volumes:
      - ./demo-medium-20170815.sql:/docker-entrypoint-initdb.d/demo-medium-20170815.sql