ARG GITHUB_TOKEN
FROM debian
RUN mkdir actions-runner && cd actions-runner
RUN curl -o actions-runner-linux-x64-2.314.1.tar.gz -L https://github.com/actions/runner/releases/download/v2.314.1/actions-runner-linux-x64-2.314.1.tar.gz
RUN echo "6c726a118bbe02cd32e222f890e1e476567bf299353a96886ba75b423c1137b5  actions-runner-linux-x64-2.314.1.tar.gz" | shasum -a 256 -c
RUN tar xzf ./actions-runner-linux-x64-2.314.1.tar.gz
RUN ./config.sh --url https://github.com/AndreyMetelkin85/test-automation-suite --token GITHUB_TOKEN
EXPOSE 49153
ENTRYPOINT ["pytest"]