version: "3.8"

services:
  allure:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:39533"
    volumes:
      - ./results:/root/results

  db_test_database:
    container_name: db_test_database
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - ./sql_file/demo-small-20170815.sql:/docker-entrypoint-initdb.d/demo-small-20170815.sql
