name: Autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - Run tests

jobs:
  test:
    runs-on: self-hosted


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.13"

      - name: Update APT
        run: sudo apt update 2>/dev/null | grep packages | cut -d '.' -f 1
      - name: Install Chrome
        run: apt-get install google-chrome-stable
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest -m "not db_test"