name: Autotest

on:
  push

jobs:
  test:
    runs-on: self-hosted


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
#      - name: setup Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: "3.9.13"
#      - name: Install Chrome
#        run: sudo apt-get install google-chrome-stable
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
